name: flutterblockit
description: "Flutter Greenfield Project"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  mocktail: ^1.0.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  dio: ^5.7.0
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.4
  jwt_decoder: ^2.0.1
  ulid: ^2.0.1
  connectivity_plus: ^6.0.5
  cached_network_image: ^3.4.1
  image_cropper: ^8.0.2
  shimmer: ^3.0.0
  collection: ^1.18.0
  url_launcher: ^6.3.1
  amplitude_flutter: ^3.16.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.1"
  bloc_test: ^9.1.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.12

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "./assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/icon.png